### PR TITLE
Migeng 663 cloudservices api list

### PR DESCRIPTION
**Pull request by jonathanvila**
https://issues.redhat.com/browse/MIGENG-663

### CODE REVIEW

**Comment by jonathanvila** [comment]
retest

**Review by carlosthe19916 — COMMENTED** [review]
@jonathanvila The PR looks good to me. The new `openapi.json` file has the correct values:
Screenshot from 2020-07-13 11-12-39

However, I noticed that the `API Documentation` UI page duplicates the values inside the "Server" dropdown selector, is this going to be fixed once this PR is merged perhaps? or maybe there is some change missing?

Peek 2020-07-13 11-06

**Comment by jonathanvila** [comment]
This duplication behaviour is described here : https://projects.engineering.redhat.com/browse/RHCLOUD-7399
Once we merge this PR they will take a look in order to fix it on their side.

**Review by carlosthe19916 — APPROVED** [review]
As discussed with @jonathanvila we will merge this PR so the openapi.json is available in CI and visible in the Docs UI Page. We will keep an eye on the response of https://projects.engineering.redhat.com/browse/RHCLOUD-7399 and wait until they fix the problem and if they require some change from our side we will create another PR

**Pull request merged**
