### PR TITLE
MIGENG-154 Filtering - Workload Inventory Report

### PR DESCRIPTION
**Pull request by carlosthe19916**
Add filter QueryParams to `/report/{id}//workload-inventory`. The new supported params are:
- provider: String - this will generate an EQUALS comparison
- datacenter: String - this will generate an EQUALS comparison
- cluster: String - this will generate an EQUALS comparison
- vmName: String - this will generate a LIKE comparison
- osName: String - this will generate a LIKE comparison
- workloads: String[] -  this will generate an EQUALS comparison using OR condition between each element of the array
- complexity: String - this will generate a LIKE comparison
- recommendedTargetsIMS: String[] - this will generate an EQUALS comparison using OR condition between each element of the array
- flagsIMS: String[] - this will generate an EQUALS comparison using OR condition between each element of the array

Every filter are connected using AND operator

### CODE REVIEW

**Comment by carlosthe19916** [comment]
This PR depends on https://github.com/project-xavier/xavier-integration/pull/27

**Comment by carlosthe19916** [comment]
My last changes added `/report/{id}/workload-inventory/available-filters` endpoint which returns the filters that will be used by the UI when filtering

**Comment by carlosthe19916** [comment]
> This PR depends on #27

That PR has been merged into master so this PR is ready to be reviewed.

**Review by mrizzi — APPROVED** [review]
This PR has been reviewed and approved together with https://github.com/project-xavier/xavier-ui/pull/33.

Thanks @carlosthe19916

**Pull request merged**
